config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :tags
  resources :accessories
  resources :cars
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

			namespace :api do
			  namespace :v1 do
			    devise_scope :user do
			      post 'registrations' => 'registrations#create', :as => 'register'
			      put 'registrations' => 'registrations#update',  :as => 'update'
			      delete 'registrations' => 'registrations#destroy', :as => 'destroy'
			      post 'sessions' => 'sessions#create', :as => 'login'
			      delete 'sessions' => 'sessions#destroy', :as => 'logout'
			    end
			  end
			end

			namespace :api do 
				namespace :v1 do 
					  resources :accessories do 
				        collection do
				          get 'get_accessories'
				        end
				      end


				end
			end
end

app/models/accessory.rb
class Accessory < ApplicationRecord
	belongs_to :car
	has_many :accessory_tags
	has_many :tags, through: :accessory_tags

end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :set_accessory, only: [:show, :edit, :update, :destroy]

  # GET /accessories
  # GET /accessories.json
  def index
    @accessories = Accessory.all
  end

  # GET /accessories/1
  # GET /accessories/1.json
  def show
  end

  # GET /accessories/new
  def new
    @accessory = Accessory.new
  end

  # GET /accessories/1/edit
  def edit
  end

  # POST /accessories
  # POST /accessories.json
  def create
    @accessory = Accessory.new(accessory_params)

    respond_to do |format|
      if @accessory.save
        format.html { redirect_to @accessory, notice: 'Accessory was successfully created.' }
        format.json { render :show, status: :created, location: @accessory }
      else
        format.html { render :new }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accessories/1
  # PATCH/PUT /accessories/1.json
  def update
    respond_to do |format|
      if @accessory.update(accessory_params)
        format.html { redirect_to @accessory, notice: 'Accessory was successfully updated.' }
        format.json { render :show, status: :ok, location: @accessory }
      else
        format.html { render :edit }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accessories/1
  # DELETE /accessories/1.json
  def destroy
    @accessory.destroy
    respond_to do |format|
      format.html { redirect_to accessories_url, notice: 'Accessory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accessory
      @accessory = Accessory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accessory_params
      params.require(:accessory).permit(:name)
    end
end

app/controllers/api/v1/accessories_controller.rb
class Api::V1::AccessoriesController < ApplicationController
	skip_before_action :verify_authenticity_token,:if => Proc.new { |c| c.request.format == 'application/json' }



  respond_to :json

  def index 
  	resource = Accessory.all
    if resource.present?
    render :status => 200,
       :json => { :success => true,:info => "list of accessories!",:data => { :accessory => resource,:auth_token => current_user.authentication_token } }
    else
      render :status => :unprocessable_entity,:json => { :success => false,:info => resource.errors, }
    end
  end

  def get_accessories
  	@accessories = Accessory.where(:car_id=>params[:accessory][:car_id]).includes(:tags).where(tags: {name: params[:accessory][:tag_name]})
  	if @accessories.present?
  		render json: @accessories, include: [:tags] ,status: 200
  	else
  		render :status => :unprocessable_entity,:json => { :success => false,:info => "404 errors", }
  	end
  end
  
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/views/accessories/_form.html.erb
<%= form_for(accessory) do |f| %>
  <% if accessory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accessory.errors.count, "error") %> prohibited this accessory from being saved:</h2>

      <ul>
      <% accessory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accessories/edit.html.erb
<h1>Editing Accessory</h1>

<%= render 'form', accessory: @accessory %>

<%= link_to 'Show', @accessory %> |
<%= link_to 'Back', accessories_path %>

app/views/accessories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accessories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accessories.each do |accessory| %>
      <tr>
        <td><%= accessory.name %></td>
        <td><%= link_to 'Show', accessory %></td>
        <td><%= link_to 'Edit', edit_accessory_path(accessory) %></td>
        <td><%= link_to 'Destroy', accessory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accessory', new_accessory_path %>

app/views/accessories/new.html.erb
<h1>New Accessory</h1>

<%= render 'form', accessory: @accessory %>

<%= link_to 'Back', accessories_path %>

app/views/accessories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @accessory.name %>
</p>

<%= link_to 'Edit', edit_accessory_path(@accessory) %> |
<%= link_to 'Back', accessories_path %>